Region: us-east-1
Image:
 Os: alinux2
HeadNode:
 InstanceType: t2.micro
 Networking:
   SubnetId: <PUBLIC SUBNET ID>
 Ssh:
   KeyName: mpilab
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: spot
    ComputeResources:
    - Name: t2micro
      InstanceType: t2.micro
      MinCount: 0
      MaxCount: 10
    Networking:
      SubnetIds:
      - <PRIVATE/PUBLIC SUBNET ID>
